### ISSUE TITLE
문서가 틀렸습니다

### ISSUE THREAD

**Issue by appkr** [routomap/routomap-api#2]
https://developers.routo.com/index.html#restapi/docs/poiTotal
<img width="843" alt="스크린샷 2022-04-19 오전 9 37 27" src="https://user-images.githubusercontent.com/6471947/163897984-cb1c3e4a-932a-4950-8a4a-f299da582667.png">

**Comment by routomap** [comment]
지적 감사합니다. 덕분에 문서 내용 바로잡았습니다.
